#include <iostream>
#include <fstream>
#include <chrono>

#include "headers/fasta.h"
#include "headers/blast.h"
#include "headers/blosum.h"
#include "headers/Protein.h"
#include "headers/SmithWaterman.h"

int main(int argc, char** argv){

    string fastafile = argv[1];
    string pinfile = string(argv[2]) + ".pin";
    string psqfile = string(argv[2]) + ".psq";
    string phrfile = string(argv[2]) + ".phr";
    string blosumfile = string(argv[3]);

    int GOP = atoi(argv[4]); // GOP = Gap Open Penalty
    int GEP = atoi(argv[5]); // GEP = Gap Extension Penalty

    query query = getIdandsequence(fastafile);
    dataPin pindata = read_pin(pinfile);
    Blosum scoring(blosumfile);
    // vector<Protein> proteins = Protein::initProtlist(phrfile, psqfile, pindata); 

    Protein fake_prot;
    fake_prot.sequence = "MEFLRGGAALLQLLLVLSISRCCSTDPDRKVCQGTSNQMTMLDNHYLKMKKMYSGCNVVLENLEITYTQENQDLSFLQSIQEVGGYVLIAMNEVSTIPLVNLRLIRGQNLYEGNFTLLVMSNYQKNPSSPDVYQVGLKQLQLSNLTEILSGGVKVSHNPLLCNVETINWWDIVDKTSNPTMNLIPHAFERQCQKCDHGCVNGSCWAPGPGHCQKFTKLLCAEQCNRRCRGPKPIDCCNEHCAGGCTGPRATDCLACRDFNDDGTCKDTCPPPKIYDIVSHQVVDNPNIKYTFGAACVKECPSNYVVTEGACVRSCSAGMLEVDENGKRSCKPCDGVCPKVCDGIGIGSLSNTIAVNSTNIRSFSNCTKINGDIILNRNSFEGDPHYKIGTMDPEHLWNLTTVKEITGYLVIMWWPENMTSLSVFQNLEIIRGRTTFSRGFSFVVVQVRHLQWLGLRSLKEVSAGNVILKNTLQLRYANTINWRRLFRSEDQSIEYDARTENQTCNNECSEDGCWGPGPTMCVSCLHVDRGGRCVASCNLLQGEPREAQVDGRCVQCHQECLVQTDSLTCYGPGPANCSKSAHFQDGPQCIPRCPHGILGDGDTLIWKYADKMGQCQPCHQNCTQGCSGPGLSGCRGDIVSHSSLAVGLVSGLLITVIVALLIVVLLRRRRIKRKRTIRCLLQEKELVEPLTPSGQAPNQAFLRILKETEFKKDRVLGSGAFGTVYKGLWNPDGENIRIPVAIKVLREATSPKVNQEVLDEAYVMASVDHPHVCRLLGICLTSAVQLVTQLMPYGCLLDYVRQHQERICGQWLLNWCVQIAKGMNYLEERHLVHRDLAARNVLLKNPNHVKITDFGLSKLLTADEKEYQADGGKVPIKWMALESILQWTYTHQSDVWSYGVTVWELMTFGSKPYDGIPAKEIASVLENGERLPQPPICTIEVYMIILKCWMIDPSSRPRFRELVGEFSQMARDPSRYLVIQGNLPSLSDRRLFSRLLSSDDDVVDADEYLLPYKRINRQGSEPCIPPTGHPVRENSITLRNISDPTQNALEKDLDGHEYVNQPGSETSSRLSDIYNPNYEDLTDGWGPVSLSSQEAETNFSRPEYLNTNQNSLPLVSSGSMDDPDYQAGYQAAFLPQTGALTGNGMFLPAAENLEYLGQGGALYTPVR";
    fake_prot.id = query.id;
    cout << SWmatrix(query, fake_prot, scoring, GOP, GEP) << endl;

    // vector<Protein> bestprots = Top20Prot(proteins, query, scoring, GOP, GEP);
    // for (int i; i < bestprots.size(); i++)
    // {
    //     cout << bestprots[i].id << " " + bestprots[i].sequence << endl;
    // }
    return 0;
}